### ISSUE TITLE
`config.store` is being ignored

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#337] opened 2019-10-15 16:22 UTC
We're trying to use a custom config to set the `store` to a different redis URL, but coverband is picking up `ENV['REDIS_URL']` instead.

It seems like coverband goes for the ENV var when it's first loaded, which seems to happen _before_ our config file is fired. And then it seems like calling `config.store = ...` has no effect.

Our config looks like this:

```
coverband_redis_url = ENV.fetch(ENV.fetch('COVERBAND_REDIS_PROVIDER'))
Coverband.configure do |config|
  config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: coverband_redis_url))
end
```

**Comment by kbaum** [comment] 2019-10-15 19:45
Thanks for bringing this up. Will take a look but for now can you try going without a coverband.rb and setting the environment variable `COVERBAND_REDIS_URL`? Coverband tries `COVERBAND_REDIS_URL` before falling back to `REDIS_URL`.

https://github.com/danmayer/coverband/blob/master/lib/coverband/configuration.rb#L217

**Comment by jagthedrummer** [comment] 2019-10-15 19:48
Yeah, that's what we did to get around the problem.

**Comment by kbaum** [comment] 2019-10-15 19:53
Gotcha. Is there any other kind of custom coverband setup logic that you have or just the coverband.rb? Also, are you using rails? If so, what eversion?

thx.

**Comment by danmayer** [comment] 2019-10-15 19:58
This feels like it is related to the changes of the configuration running multiple times previously... My best guess is that it worked in the past because it failed on first config, and succeeded later...

This is also likely related to the ENV load ordering, these two combined can cause all sorts of confusion. As people have upgraded we have had many folks using `dotenv`, `mc_settings`, and others hitting issues... 

We added a section in our readme about it... Do you use anything to manage environment variables, if so take a look @jagthedrummer  It could be as simple as ordering.

https://github.com/danmayer/coverband#working-with-environment-variables

**Comment by danmayer** [comment] 2019-10-15 20:07
any details on your coverband config file could also be helpful... if they have conditionals dependent on env vars, etc for exmaple.

**Comment by jagthedrummer** [comment] 2019-10-15 21:01
We're on rails 5.2.3 and coverband 4.2.0.

Our entire config looks like this:
```ruby
  coverband_percentage = ENV.fetch('COVERBAND_PERCENTAGE', 0.0).to_f
  if coverband_percentage > 0
    require 'coverband'
    coverband_redis_url = ENV.fetch(ENV.fetch('COVERBAND_REDIS_PROVIDER'))
    track_gems = ENV.fetch('CLICKFUNNELS_COVERBAND_TRACK_GEMS', 'true') == 'true'

    Coverband.configure do |config|
      config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: coverband_redis_url))
      config.track_gems = track_gems
    end
  end
```

The problem is happening in heroku, where we're using their normal config vars to inject things into the ENV before the app boots.

**Comment by kbaum** [comment] 2019-10-15 21:32
Is that code all defined within ./config/coverband.rb?

If so, would it be possible to simplify it by removing the coverband percentage and instead rely on `ENV['COVERBAND_DISABLE_AUTO_START']`? This way there is no need to require coverband within your coverband.rb. Something like:

```ruby
   coverband_redis_url = ENV.fetch(ENV.fetch('COVERBAND_REDIS_PROVIDER'))
   track_gems = ENV.fetch('CLICKFUNNELS_COVERBAND_TRACK_GEMS', 'true') == 'true'
   Coverband.configure do |config|
     config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: coverband_redis_url))
     config.track_gems = track_gems
   end
```

Then to disable coverband, just set COVERBAND_DISABLE_AUTO_START. Since coverband uses ruby standard lib coverage now, it no longer supports COVERBAND_PERCENTAGE unless I am misunderstanding the intention of that environment variable.

**Comment by jagthedrummer** [comment] 2019-10-15 22:10
Yes, that's all in `config/coverband.rb`. The `COVERBAND_PERCENTAGE` ENV variable is just a hold-over from when coverband did support an actual sampling percentage. We've sort of adapted it to be our "is coverband on or off?" flag. And, for purposes of being able to know exactly when/if coverband is loading, we wanted the manual require. Do you think that is causing the ignoring of `config.store`?

**Comment by danmayer** [comment] 2019-10-15 22:21
I think having `require 'coverband'` inside the coverband config would cause issues... I am thinking it previously worked because we allowed the coverband configuration to be called multiple times, so it would fail once and then work on the next run. 

I recommend wrapping that conditional inside your `application.rb` just after the bundler setup code `Bundler.require(*Rails.groups)` or to rely on the new `COVERBAND_DISABLE_AUTO_START`
Give that a shot and let us know @jagthedrummer... sorry for the change on load order, that small perf fix, had more bugs and upgrade issues than we would have anticipated.

**Comment by kbaum** [comment] 2019-10-16 00:48
So just tried this out on coverband_demo project on this branch but wasn't able to reproduce the issue:

https://github.com/danmayer/coverband_demo/compare/try_reproduce_redis_url

![image](https://user-images.githubusercontent.com/96786/66879663-257eb980-ef8d-11e9-80f8-4d6c0de360c8.png)

Let me know what you think.

**Comment by danmayer** [comment] 2019-10-17 19:31
any word on things like `dotenv` or other gems that configure the environment @jagthedrummer

**Comment by jagthedrummer** [comment] 2019-10-17 20:33
@danmayer as I mentioned before this is happening in heroku where we don't use anything other than their standard config variables which they inject into the ENV. So `dotenv` and the like are most definitely not involved.

**Comment by kbaum** [comment] 2019-10-17 21:27
@jagthedrummer - Not sure if you noticed my comment but I tried to reproduce this issue locally but unfortunately was unsuccessful:

https://github.com/danmayer/coverband/issues/337#issuecomment-542462803

Can you have a look and let us know how your setup differs to that example from the coverband_demo branch?

Also, are you able to reproduce this issue on your local dev environment or just on Heroku?

Thanks.

**Comment by danmayer** [comment] 2019-10-17 23:10
> @danmayer as I mentioned before this is happening in heroku where we don't use anything other than their standard config variables which they inject into the ENV. So `dotenv` and the like are most definitely not involved.

oops, sorry I missed that response I think...

Back to this, "I think having require 'coverband' inside the coverband config would cause issues... " From this comment,  https://github.com/danmayer/coverband/issues/337#issuecomment-542429659

Did you try moving that?

**Comment by jagthedrummer** [comment] 2019-10-23 20:02
I also haven't been able to reproduce the problem locally, only in heroku.

The config in that branch looks pretty close to what we're doing.

I'll try removing the `require` and then see if we can run another test. It may be a few days though. Thanks for looking into it!

**Comment by danmayer** [comment] 2019-10-23 20:03
Thanks, no worries... Let us know what you find. Working on prepping a next small release so if we figure it out and get a fix in great. If not we can always add it when ever we sort it out.

**Comment by kbaum** [comment] 2019-10-24 19:37
Interesting about only being to reproduce on Heroku. I haven't tried the example I game earlier on heroku.

**Comment by danmayer** [comment] 2019-11-19 02:38
OK, great thanks for letting us know, yeah definitely all seems like it could be related.

**Comment by danmayer** [comment] 2020-04-15 02:41
OK, this looks like it was resolved in thread closing this out

**Closed by danmayer** 2020-04-15 02:41 UTC
