### ISSUE TITLE
Rack application to view production coverage without the need of S3

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#147] opened 2018-12-01 23:20 UTC
Coverband should come with a mountable rack application for viewing coverage straight from the store in real time. This would remove the need to run a rake task to generate a report along with the need to push the report to an s3 bucket.

Another benefit would be that it would give us control around the data we display. For example, how long we've been collecting coverage on the current file.

Wanted to open this issue to start thinking about how we would approach this one.

**Comment by danmayer** [comment] 2018-12-01 23:33
yep, this is already on the roadmap, I have almost started it a couple of times but decided the background threading and railties stuff was more important. I want to remove the simplecov-html dependency and pull more of that into the gem.

outlined a bit here:
https://github.com/danmayer/coverband/blob/feature/railtie/changes.md#coverband-4x

**Comment by kbaum** [comment] 2018-12-02 14:09
This seems relatively straight forward. Have you thought about UI? Something like a bootstrap 4 table with filtering built in?

https://getbootstrap.com/docs/4.0/content/tables/

Think it could also benefit from some pagination and client side filtering. Listing all of the files on a large project can make the browser a little unresponsive.

**Comment by danmayer** [comment] 2018-12-04 22:06
updated description the rack app already doesn't need the rake task you can trigger coverage collection, write the s3 report, clear data, etc from the app... The issue is that S3 is needed / used for report storage... And we want to just have a nice view on the actual data...

We could have a very simple view with tables but I think we want to view the source code as it is a bit hard to interpret without it. I think some of the basic code style stuff is kind of nice but perhaps could be avoided.

One question before digging in on local rendering... I believe some of githubs new integration features allows one to overlay stuff like this on the source code view... would that be a better approach or worse because it ties the project very tightly to github. Could be an interesting way to view things, but I am guessing we want to keep local views for now.

**Comment by kbaum** [comment] 2018-12-05 00:10
@danmayer Agreed on viewing source being super important. Forgot about that part.

RE: Overlaying onto github source code view. That sounds very interesting... only problem might be that we wouldn't be supporting other source control repos like bitbucket etc.

**Comment by danmayer** [comment] 2018-12-05 04:48
OK, I will kick off work on this sometime this week. I have a good thought on how to initially bootstrap something quickly that we can build off of. As for Github I think it is cool, but perhaps an optional adapter vs the source code view.

**Comment by kbaum** [comment] 2018-12-05 13:07
Ok great. Let me know if i can help.

**Comment by danmayer** [comment] 2018-12-06 03:00
Cool thanks... probably a bit hard to help on this specific part until I get something workable... I might have something good enough to kick off PR discussion later tonight, the current path is looking really promising. 

Other things that could be worked on:

**Comment by danmayer** [comment] 2018-12-06 03:04
Cool thanks... probably a bit hard to help on this specific part until I get something workable... I might have something good enough to kick off PR discussion later tonight, the current path is looking really promising.

If you are looking for some random Coverband stuff ;) Other things ready for work, if not no worries:
* adding background jobs or cron jobs to coverband_demo to show they work
* add additional config / protection options on Coverage clear blocking it from being run on web
* another pass on readme and moving some things to wiki
* github issue template, setting up a good one

**Comment by danmayer** [comment] 2018-12-06 05:12
OK, still a bunch to be done... but @kbaum this works and gets full control of the rendering, assets, and calculations into Coverband... https://github.com/danmayer/coverband/pull/148

Only needed small amounts of changes to get it functional after pulling selected files in.

It needs some further cleanup as I think we don't need / use all of the feature set. Also, I need to decide which tests to pull in as well.

**Comment by danmayer** [comment] 2018-12-29 21:43
ok, @kbaum I merged in the branch and improved the web UI a bit more... take a look at the new Coverband admin web https://coverband-demo.herokuapp.com/coverage/#_AllFiles

This is released at 4.0.1.beta and I think it might be good enough for the 4.0.1 release after some documentation updates, but let me know.

**Comment by kbaum** [comment] 2018-12-30 13:11
@danmayer Looks great! Agreed being ready for 4.0.1. :shipit:

**Comment by danmayer** [comment] 2018-12-30 20:47
live in release 4.0.1

**Closed by danmayer** 2018-12-30 20:47 UTC
