### ISSUE TITLE
Provide the Ability to Manually Clear Coverage

### ISSUE THREAD

**Issue by amw-zero** [danmayer/coverband#216] opened 2019-03-20 18:51 UTC
The main use case for manually clearing the coverage for a file is for when the caller of a class changes, but the implementation of the class does not. An example of that is when the caller passes data differently into a method and a branch in that method stops being taken.

In this case, it would be useful to be able to manually clear the coverage that way you can start recollecting it after the calling code changes to verify its effect on the called code.

Example receiving code:

```
```

**Comment by danmayer** [comment] 2019-03-21 02:05
closing as duplicate of #217

**Closed by danmayer** 2019-03-21 02:05 UTC
