### ISSUE TITLE
Exclude clear coverage report by default

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#159] opened 2018-12-30 15:12 UTC
We are now resetting coverage for each file whenever there is any change. Because of this, I am not sure it makes sense to offer the ability to "clear coverage report" from the admin. This seems like it could do more harm than good. 
![image](https://user-images.githubusercontent.com/96786/50548451-c082ee80-0c1a-11e9-879e-d2e57422c490.png)
Perhaps we make this configurable and off by default?

Also not sure "force coverage collection" makes sense considering we have a background thread reporting every 30 seconds by default. Just thinking that having less might make coverband simpler out of box.

**Comment by danmayer** [comment] 2018-12-30 16:10
The force collection has been helpful for testing and debugging, I think it has also been helpful for folks that collect coverage while running selenium against an external server... but perhaps it is more helpful as an API than a button.

I am +1 on moving clear coverage to a configurable off by default... 

I do think driving via API the flow for running selenium tests is something like this...

* deploy new code
* clear all coverage
* run selenium tests
* force collect coverage
* generate report

Perhaps some of that could be made easier by just having some client API hooks that could be calls from a test suite similar to the rake tasks.

**Comment by kbaum** [comment] 2018-12-30 19:55
Ok. I think "clear coverage report" is the much riskier one anyway.

RE: selenium use case. Why would people prefer to measure selenium coverage in production versus running automated tests in a continuous build type environment? I feel like the major use case of selenium is to measure what real users are actually hitting in production vs an automated script which can be run against a non-production environment.

**Comment by danmayer** [comment] 2019-01-06 21:02
@kbaum  I would need to talk to selenium users more as I don't use Coverband this way but have heard from a number of folks that do. My understanding is they are running these in an automated fashion but against a full staging deployed server so the standard SimpleCov tooling doesn't work for them. Coverband seems to be helpful for folks doing large QA project against staging environments... I am guessing regression testing before large releases (not for folks that do continuous deployment)... but honestly, since I don't do this it would be good to better understand these users. 

The other use case Brian mentions is interesting for actually Manual QA to validate that their testing covered various flows. Which is kind of cool.

I will hide clear by default since folks seem so concerned about it being done on accident but I don't see good reason to hide force coverage, so I will keep it around.

**Comment by kbaum** [comment] 2019-01-06 21:32
Ok. Makes sense!

**Comment by danmayer** [comment] 2019-01-06 22:01
OK this was committed on master branch

**Closed by danmayer** 2019-01-06 22:01 UTC
