### ISSUE TITLE
Viewing Static HTML file from S3

### ISSUE THREAD

**Issue by kejordan** [danmayer/coverband#363] opened 2020-01-10 18:11 UTC
I'm saving reports to S3, can download them, but then cannot view them.  
When I run the rake task locally, I get the window with the report, but I also cannot download and view that s3 file.  
When I look at the developer tools, it gives a failed to load resource error.  Is there either a way to get a complete html file sent to S3? Or am I just not retrieving the assets and need to change something on my end?

**Comment by kbaum** [comment] 2020-01-10 19:49
I have not used the s3 functionality since we released the mountable rack app which allows to view the report directly in your rails app with real time data. See demo here:

https://coverband-demo.herokuapp.com/coverage?#_AllFiles

Here's how to mount it:

https://github.com/danmayer/coverband#coverage-report

Would that fit your needs or do you still have a reason to export to s3?

**Comment by kejordan** [comment] 2020-01-10 20:12
I was hoping to use S3 - we have a lot of custom routing that is a big challenge to untangle, so mounting the rack app isn't straightforward for us. 

It seemed like S3 could be an easier solution, but if its not supported, we may just need to figure out the routing

**Comment by danmayer** [comment] 2020-01-10 20:20
I think for now we have still supported it as a number of apps including those that don't support a front end / views need it...

I believe since it isn't used often we have from time to time broken inlining the assets... Let me take a look a bit later today or the weekend to see if I can still rendering the S3 file with all assets inlined.  @kejordan

**Comment by kejordan** [comment] 2020-01-10 20:37
Thanks!

**Comment by danmayer** [comment] 2020-01-12 17:20
OK, it had been some time since I looked at the S3 part of the code... I was able to reproduce the issue

<img width="1675" alt="Screen Shot 2020-01-12 at 10 15 45 AM" src="https://user-images.githubusercontent.com/24925/72222661-96018c00-3524-11ea-98c4-eb328009fcd5.png">

Either we always had to copy some assets to the file location or at some point we broke fully inlining the CSS and JS. We are planning to move away from the S3 method of reports at some point in the future, so I don't think we will work to restore a fully inlined S3 file (it would still miss some icon images and such)...

What I recommend is if you on a local machine run `rake coverband:coverage` once it will generate the local coverage in your `coverage` file along with all the needed assets.

```
ls coverage
application.css    colorbox           favicon.png        favicon_red.png    images             loading.gif
application.js     dependencies.js    favicon_green.png  favicon_yellow.png index.html         magnify.png
```

Then you can download the S3 file and replace the `index.html` locally and everything should load fine. If you are trying to set up coverband so that you can view it from a public (not good for private source code) 
or a protected bucket (I have done this via a protected S3 bucket served by Jenkins), you can upload all of the assets to the S3 bucket and then view the file from S3 without issue. The assets you need to upload are the same as above in the generated coverage folder.

Let me know if either of these solutions work well enough for you @kejordan

**Comment by kejordan** [comment] 2020-01-13 14:27
Those solutions absolutely work! Thanks for your help!

**Comment by danmayer** [comment] 2020-01-13 15:30
great, glad to hear it, closing this one out then. Thanks, for reporting, @kejordan also when we remove S3 support we are hoping to have an alternative solution to viewing Coverage data that doesn't require a self-hosted route.

**Closed by danmayer** 2020-01-13 15:30 UTC
