### ISSUE TITLE
Not working on Puma multithreaded server with startup_delay turned on

### ISSUE THREAD

**Issue by mlovic** [danmayer/coverband#77] opened 2016-12-23 08:50 UTC
I've been trying to use coverband on a Rails application running on the Puma webserver using the example configuration, but coverage was always disabled. 

After digging around for a while I noticed that `Coverband::Base` holds a `@delay` instance variable which gets decreased on each request until it hits zero, at which point coverage is enabled. Puma, however spawns a new thread for each request, so a new instance of `Coverband::Base` is created with its `@delay` variable set to the original number specified in the config. This way, it never reaches zero and coverage is always disabled.

I don't know if there's an easy (and threadsafe) fix for this, but I think it should at least be documented in the README. Everything seems to work fine with `startup_delay` set to 0.

Please let me know if there's anything I'm missing.

I'd be happy to help with either docs or code!

**Comment by danmayer** [comment] 2016-12-23 17:26
hmm good find, haven't seen that. I am running most projects on puma and should be able to fix this... I will take a look this week.  Yeah `startup_delay 0` should work fine may have a slight performance hit to your first couple requests... probably not if you are using `preload_app` actually.

**Comment by danmayer** [comment] 2016-12-26 19:30
Could you send over a bit more information @mlovic so I could reproduce... I setup Coverband on a small test app... Made sure it worked and then boot my server using `puma` and it still worked

https://github.com/danmayer/travel_calculator/commit/ab730765dd9c9d37505cd23673ba8eb1d84d936a

guessing default puma might not trigger the issue because of `Puma starting in single mode...` which seems to be the default. Could you share some of your `config.ru` and Puma configuration (possibly in `config/puma.rb`) so I could make my test system behave more like your system?

**Comment by danmayer** [comment] 2016-12-26 19:35
hmmmm ok added some configs @mlovic and now booting puma in cluster mode and coverband still works with startup_delay of 2.

`[69764] Puma starting in cluster mode...`

my `config/puma.rb`

```
root = File.expand_path('../..', __FILE__)
env ||= ENV['RACK_ENV'] || 'development'

if env=='staging'
  workers (ENV['WEB_CONCURRENCY'] || ENV['PUMA_WORKERS'] || 2).to_i
  max_threads = (ENV['MAX_THREADS'] || ENV['PUMA_WORKER_THREADS'] || 3).to_i
else
  workers (ENV['WEB_CONCURRENCY'] || ENV['PUMA_WORKERS'] || 2).to_i
  max_threads = (ENV['MAX_THREADS'] || ENV['PUMA_WORKER_THREADS'] || 10).to_i
end
threads max_threads / 2, max_threads

preload_app!

rackup DefaultRackup
port ENV['PORT'] || 3000
environment env

bind 'unix:///tmp/puma.sock'

pidfile "#{root}/tmp/pids/puma.pid"

stdout_redirect "#{root}/log/puma.stdout.log", "#{root}/log/puma.stderr.log", true

before_fork do
  ActiveRecord::Base.connection_pool.disconnect!
end

after_worker_boot do
  Kernel.rand
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

my `config.ru`

```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)

require 'coverband'
Coverband.configure

run Rails.application
```

If you are by chance running Coverband via a Rails initializer perhaps send me the code where you set it up, and I could take a look... guessing either initializer vs `config.ru` could cause loading pre vs. post fork... Or that you don't have `preload_app!` in your `puma.rb`... If we can track down to repo, I can likely update docs or detect when it happens and provide an error.

Thanks.

**Comment by mlovic** [comment] 2016-12-26 20:26
Hi @danmayer. Thanks for the response! 

Sure, here's some of my configuration:

config.ru

```ruby
require ::File.expand_path('../config/environment',  __FILE__)
run Rails.application
```

config/puma.rb (started in cluster mode)

```ruby
environment ENV['RACK_ENV'] || 'development'
threads ENV['MIN_PUMA_THREADS'] || 0, ENV['MAX_PUMA_THREADS'] || 16
workers ENV['PUMA_WORKERS'] || 1
preload_app!

on_restart do
  ::Redis.current.quit
end
```

config/coverband.rb

```ruby
Coverband.configure do |config|
  config.root              = Dir.pwd
  if defined? Redis
    redis_url = ENV[ENV['REDIS_PROVIDER'] || 'REDIS_URL'] || 'redis://localhost:6379'
    config.redis           = Redis.new(url: redis_url, db: 4)
  end
  config.coverage_baseline = Coverband.parse_baseline
  config.ignore            = ['vendor','lib']
  # OPTION NOT WORKING WITH PUMA
  #config.startup_delay     = Rails.env.production? ? 15 : 3
  config.startup_delay     = 0
  config.percentage        = Rails.env.production? ? 20.0 : 100.0
  config.logger            = Rails.logger
  config.verbose           = Rails.env.production? ? false : true
end
```

config/application.rb

```ruby
class Application < Rails::Application
    config.middleware.use Coverband::Middleware
...
```

config/initializers/coverband_middleware.rb

```ruby
require 'coverband'
Coverband.configure
```

I also added some logging to the Coverband source while testing the other day:

```ruby
module Coverband
  class Base

    def self.instance
      p Thread.current
      Thread.current[:coverband_instance] ||= Coverband::Base.new
    end
```

  On every request the thread was different, even with puma workers and max_threads set to 1.

**Comment by danmayer** [comment] 2016-12-26 20:53
Awesome thanks I will set my app up like that and see if I can get it to reproduce... it makes sense to me that this error could occur, but so far no luck triggering it.... headed out for now so I will check it later

**Comment by danmayer** [comment] 2016-12-27 00:26
hmm so weird... I still have no issue after making my puma.rb the same as yours and moving to an initializer... 

ahh ok added your logging and looks like I have reproduced... but I hit the count per thread pretty quickly in my example app as it is even triggered for assets in my dev setup. Below shows 3 different threads for 3 requests... 

```
#<Thread:0x00000109c72f40>
**************************************************

Started GET "/assets/controllers/TripController.js?body=1" for 127.0.0.1 at 2016-12-26 17:22:59 -0700
#<Thread:0x00000109c71af0>
**************************************************
#<Thread:0x00000109c71af0>
**************************************************
Started GET "/assets/directives/calendar.js?body=1" for 127.0.0.1 at 2016-12-26 17:22:59 -0700
#<Thread:0x00000109c70ee8>
```

Thanks OK, now with a repro let me look at best way to resolve this tomorrow.

**Comment by mlovic** [comment] 2016-12-27 15:04
That makes sense. I've only been using the application's API (should have thought to mention it), so no assets. I just tried an HTML route and I'm seeing the same thing. 

```
15:46:57 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:57 web.1    | Startup delay: 3
15:46:57 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:57 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:57 web.1    | [6923] 127.0.0.1 - - [27/Dec/2016 15:46:57] "GET /unauthenticated HTTP/1.0" 302 - 0.1626
15:46:57 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:57 web.1    | Startup delay: 2
15:46:57 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:58 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:58 web.1    | [6923] 127.0.0.1 - - [27/Dec/2016 15:46:58] "GET /admin_users/sign_in HTTP/1.0" 200 - 1.4893
15:46:59 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:59 web.1    | Startup delay: 1
15:46:59 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:59 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:59 web.1    | [6923] 127.0.0.1 - - [27/Dec/2016 15:46:59] "GET /admin/base.css?body=1 HTTP/1.0" 200 401098 0.0631
15:46:59 web.1    | #<Thread:0x007fa810be9aa0 run>
15:46:59 web.1    | Startup delay: 0
15:46:59 web.1    | #<Thread:0x007fa810be9aa0 run
```

All asset requests are fulfilled by the same thread, and the startup delay decreases with each one. Then for the next request/transaction, a different thread is used, and startup delay is reset to the original 3:

```
15:47:01 web.1    | #<Thread:0x007fa810be9aa0 run>
15:47:01 web.1    | Startup delay: 0
15:47:01 web.1    | #<Thread:0x007fa810be9aa0 run>
15:47:01 web.1    | #<Thread:0x007fa810be9aa0 run>
15:47:01 web.1    | [6923] 127.0.0.1 - - [27/Dec/2016 15:47:01] "GET /vendor/modernizr.js?body=1 HTTP/1.0" 200 51352 0.0362

# Next HTML/document request...

15:50:19 web.1    | #<Thread:0x007fa812d63938 run>
15:50:19 web.1    | Startup delay: 3
15:50:19 web.1    | #<Thread:0x007fa812d63938 run>
15:50:19 web.1    | #<Thread:0x007fa812d63938 run>
15:50:19 web.1    | [6923] 127.0.0.1 - - [27/Dec/2016 15:50:19] "GET /unauthenticated HTTP/1.0" 302 - 0.0326
15:50:19 web.1    | #<Thread:0x007fa812d63938 run>
15:50:19 web.1    | Startup delay: 2
15:50:19 web.1    | #<Thread:0x007fa812d63938 run>
```

I guess puma only spawns a new thread for each HTTP transaction / TCP connection.

**Comment by danmayer** [comment] 2016-12-27 16:01
OK cool after looking a bit more I think this makes sense as intended behavior so I just updated the readme to try to make the case for threaded servers and how they react to the startup delay more clear. Thanks for the report and this thread will also help anyone searching for the issue.

**Closed by danmayer** 2016-12-27 16:01 UTC
