### ISSUE TITLE
Rake static html coverage report not working

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#248] opened 2019-05-05 13:14 UTC
Tried generating the html coverage report from master. Debugged the task a bit and see that it is making [this call](https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/tasks.rb#L14):

```ruby
Coverband::Reporters::HTMLReport.report(Coverband.configuration.store)
```

Which is ending up in the [Base::report](https://github.com/danmayer/coverband/blob/master/lib/coverband/reporters/base.rb#L12) class method. Not sure if this is intended but when i changed the rake task to use the instance report method as opposed to class, I get a report:

```ruby
Coverband::Reporters::HTMLReport.new(Coverband.configuration.store).report
```

Not exactly sure what was intended. One other note is I am a little confused by this method in HTMLReport:

```ruby
      def report
        if html
          Coverband::Utils::HTMLFormatter.new(filtered_report_files,
                                              base_path: base_path,
                                              notice: notice).format_html!
        else
          Coverband::Utils::HTMLFormatter.new(filtered_report_files).format!
          if open_report
            `open #{Coverband.configuration.root}/coverage/index.html`
          else
            Coverband.configuration.logger.info 'report is ready and viewable: open coverage/index.html'
          end

          Coverband::Utils::S3Report.instance.persist! if Coverband.configuration.s3_bucket
        end
      end
```

In this method we check if it's an html report which evaluates to false in my case but then in the else block, we end up generating and opening up an html report. Wondering if we still need all of these branches?

thx.

**Comment by danmayer** [comment] 2019-05-05 16:42
hmmm, OK let me take a look... That branching we can make more clear this gets into one returns HTML as a string for the web server That is the `if html` case. Perhaps we can call that dynamic_html and the other case is static HTML written to a local file. The Rake task uses the static HTML written to the file.

In terms of the bug I don't really understand the top part about the call to the class vs instance method from the description, but I can likely figure that out pretty quickly by running. I just got all of this under pretty good tests, so I am curious to see where the disconnect in the test vs the Rake task is and hopefully resolve that.

**Comment by danmayer** [comment] 2019-05-05 18:13
yep looks like I broke this during this refactoring here: 
https://github.com/danmayer/coverband/commit/d019b370adbdea4c625158b18f1cdce257a6375f#diff-0c30a7c863d6f2f72ed19d5f41f15950

pushed fix on the current PR branch for this as well, but still need to revisit how to test this to avoid regressions

**Closed** 2019-05-06 16:29 UTC
