### ISSUE TITLE
Manually starting coverband causes load-time coverage to be reported as runtime

### ISSUE THREAD

**Issue by maxp-hover** [danmayer/coverband#365] opened 2020-01-13 20:23 UTC
This is ironically the opposite as the problem we were discussing last week ... load time coverage is being reported as runtime ...

The readme mentions that `COVERBAND_DISABLE_AUTO_START ` can be used to prevent `require 'coverband'` from automatically starting coverage. This is our use-case - we want to use a feature flag to _enable_ coverband.

1. In the Gemfile, I have `require 'coverband'`
2. Start rails console with `COVERBAND_DISABLE_AUTO_START=true`
3. Inside `config/intitializers/coverband.rb`, call `Coverband.start`
4. Observe on the web interface that all coverage is being reported as runtime

**Comment by kbaum** [comment] 2020-01-13 20:40
I think the issue is that the initializer is being run after the classes have been eagerly loaded. Can you instead require coverband at the top of application.rb?

**Comment by maxp-hover** [comment] 2020-01-13 20:48
@kbaum I will try that. Thanks for responding so quickly! 
 
By the way (and sorry to be tangential / hijack the issue) do you know of a way to configure reporting for _only_ a couple of files? Or is it currently only possible to _ignore_ certain files?

**Comment by maxp-hover** [comment] 2020-01-13 20:57
@kbaum putting it at the top of application.rb does not work, because in order to conditionally enable/disable it I need to perform a database call, and the database connection does not seem to be set up by that point.

**Comment by kbaum** [comment] 2020-01-13 22:20
Hmmm.. i don't know of a way around that one. Are there any alternatives to storing in the database? Perhaps an environment variable or redis?

**Comment by maxp-hover** [comment] 2020-01-13 22:32
@kbaum Yes we have considered that, but we would rather not change our whole feature flag system. And besides, reporting usage as runtime vs load-time isn't really the end of the world - it might not be worth the trade-off for us in terms of consistency with our feature flag system. 

I suppose we can close this one if you don't think it's a problem worth fixing, or maybe there isn't really a feasible fix. I do have one other question, but rather than hijack this issue, I'll open another one. Thanks so much for your attention, we really appreciate it here at Hover.

**Comment by danmayer** [comment] 2020-04-13 02:57
yeah Sorry @maxp-hover I can't think of any alternatives if you need to hit the DB and lazily decide to load coverband. I think we could perhaps work on making the whole concept of eager vs runtime coverage optional. I will consider that as we look to refactor and rip out some things that never fully panned out. 

I will close this out for now.

**Closed by danmayer** 2020-04-13 02:57 UTC
