### ISSUE TITLE
Increased CPU usage in v4.2.0

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#252] opened 2019-05-07 17:51 UTC
We updated to coverband 4.2.0 a while back from 4.0.1 and we've noticed steadily increasing CPU usage ever since. After disabling coverband entirely it returned to "normal" levels. At the same time that we updated to 4.2.0 we also enabled gem tracking, but turning off gem tracking by itself didn't seem to have any effect.

Here are some screenshots to illustrate what we're seeing.

A few days worth of CPU after we updated to 4.2.0 showing steadily increasing CPU utilization:
<img width="1618" alt="Screen Shot 2019-05-07 at 12 24 18 PM" src="https://user-images.githubusercontent.com/58702/57321095-23532d80-70c6-11e9-8dad-567906465fce.png">

CPU utilization declining after we disabled coverband:
<img width="1625" alt="Screen Shot 2019-05-07 at 12 12 44 PM" src="https://user-images.githubusercontent.com/58702/57321104-2c43ff00-70c6-11e9-8abd-c704e77f35d7.png">

The main reason we're concerned about this is that it's had a noticeable effect on latency, especially in the upper percentiles. (The blue line is p95, yellow is p90, and purple is p75.)

Latency slowing increasing after updating to 4.2.0:
<img width="1619" alt="Screen Shot 2019-05-07 at 12 30 03 PM" src="https://user-images.githubusercontent.com/58702/57321196-72995e00-70c6-11e9-9ff7-dfa1869dd2d0.png">

Latency decreasing after disabling coverband:
<img width="1618" alt="Screen Shot 2019-05-07 at 12 36 23 PM" src="https://user-images.githubusercontent.com/58702/57321244-89d84b80-70c6-11e9-86d2-1957e7b2f972.png">

I'm sure that _some_ increase in CPU and latency is to be expected, but it seems like something big changed between 4.0.1 and 4.2.0.

**Comment by danmayer** [comment] 2019-05-07 18:02
hmm thanks for reporting @jagthedrummer we introduced the load vs runtime coverage in 4.2.0 and that seems likely to be the cause. I will try to dig in further. I release on a fairly high traffic volume site and didn't notice such a change.

Could you attach the basic Coverband config settings you have to help with debugging? I am assuming you are using the background thread reporting (now default) not the rack request reporting (old defaults in Coverband 3.x).

Also, any details like which server (puma?), background worker (sidekiq, resque, etc) would be helpful.

**Comment by danmayer** [comment] 2019-05-07 18:14
Oh, I should mention that I don't have the gem support enabled on high traffic sites yet, I believe there are still some performance overhead concerns with enabling. 

Particularly, in your config please share how you set the ignore, we had a recent report that it can re-enable gem tracking when following the old readme. This might be the cause of the issue you are having, my best guess at the moment.

https://github.com/danmayer/coverband/issues/230

I expect to make an improvement to ensure either the `=` or `+=` usage does what users expect for the next release.

**Comment by jagthedrummer** [comment] 2019-05-07 18:26
Here's our `config/coverband.rb`
```
if ENV['COVERBAND_REDIS_PROVIDER']
  coverband_redis_url = ENV.fetch(ENV.fetch('COVERBAND_REDIS_PROVIDER'))
  track_gems = ENV.fetch('CLICKFUNNELS_COVERBAND_TRACK_GEMS', 'true') == 'true'

  Coverband.configure do |config|
    config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: coverband_redis_url))
    config.track_gems = track_gems
  end
end
```

We're using Phusion Passenger as the webserver, and sidekiq for background work.

We have this sidekiq middleware in `config/initializers/coverband_middleware.rb`
```
if Rails.configuration.coverband_enabled
  require 'coverband'

  # This wraps all of our background calls to test coverage
  class Etison::CoverbandMiddleware
    def before_perform
      Coverband.start
    end

    def after_perform
      Coverband::Collectors::Coverage.instance.report_coverage
    end

    def call(worker, msg, queue)
      before_perform
      yield
      after_perform
    end
  end
end
```

And in `config/initializers/sidekiq.rb` we do this:
```
Sidekiq.configure_server do |config|
  # ...

  if Rails.configuration.coverband_enabled
    config.server_middleware do |chain|
      chain.add Etison::CoverbandMiddleware
    end
  end

  # ...
end
```

**Comment by jagthedrummer** [comment] 2019-05-07 18:30
I don't know if it's related or should be a seperate ticket, but it may be worth mentioning that earlier this week, before disabling coverband entirely we noticed that we could no longer hit the `/coverage` web route. It would constantly run longer than 25 seconds and the request would be killed by heroku.

**Comment by danmayer** [comment] 2019-05-07 18:30
Cool thanks, I will look at this. I haven't used Passenger for years, so I might need to dig into their model a bit to make sure we aren't doing anything that wouldn't work well with it's default setup, we previously learned that we had to detect and handle some odd cases for the default Resque setup, not currently aware of any issues with Passenger, but I can take a look.

Also, if you switch from having gem tracking to disabling, I would recommend clearing coverage as it has to process and ignore a lot of gem coverage data once it gets into the storage.

**Comment by danmayer** [comment] 2019-05-07 18:43
the slow reporting is almost certainly the attempts at processing the gem coverage data that get in while enabled, so ensure gem_tracking is disabled and clear the Coverband data via the rake task or via Redis.

**Comment by kbaum** [comment] 2019-05-07 18:54
Just quickly looking at this. We should not need the custom middleware for rack or sidekiq as coverband launches a background thread by default. Basically it dumps coverage data to redis every 30 seconds and also when the process exits. This could help with the CPU as coverband would be running much less frequently.

**Comment by danmayer** [comment] 2019-05-07 19:11
Yeah good call @kbaum I think when upgrading from 4.0 we should have made it more obvious the new styled do not need these sort of custom integrations.

Those should all be removed as Cover and is now doing double duty and reporting multiple ways.

I wonder if we could detect and give a good understandable error if multiple integration points are detected. I am about to fly so I will dig in more later, but the custom rack middleware would cause significant overhead for sure.

**Comment by jagthedrummer** [comment] 2019-05-07 20:13
Thanks y'all. I'm going to do the following and then will report back (it might take a few days).

* Remove our custom middleware
* Clear our coverband redis
* Re-enable coverband (without gem tracking)
* Monitor CPU usage

**Comment by danmayer** [comment] 2019-05-08 02:35
yeah I think you can also remove the custom sidekiq work if background reporting is enabled, which it now is by default it should work for sidekiq as well without any middleware require.

Clearly, when we make these changes we need to make them much more obvious to folks updating. Our goal is that no one needs to write custom Coverband middleware of any sort anymore. If there are features you feel we don't support let us know and we can try to ensure our middleware offers configurable options to help support other use cases.

In this case I think y'all were just ahead of the curve for most users and had added custom code which used to be required by now should work out of the box.

**Comment by jagthedrummer** [comment] 2019-05-08 17:04
Ok, I've removed our custom middleware, cleared redis, and re-enabled coverband.

The `/coverage` endpoint is now working (and is fast), and so far we're not seeing any noticable increase in CPU usage, but last time it took a day or two to really start creeping up, so it's hard to say for sure. I'll keep an eye on it and let you know how it goes.

**Comment by kbaum** [comment] 2019-05-08 17:21
Great to hear! Thanks for the update!

**Comment by danmayer** [comment] 2019-05-08 22:10
Yeah that is good to hear, sorry again for the confusion on the upgrade ;)

Let us know how it goes the next few days. I am going to work on a few more performance improvements related to gem support for our next release and plan to roll it out on some high capacity apps before the next official release to ensure we have resolved the gem related performance overhead.

**Comment by jagthedrummer** [comment] 2019-05-15 13:59
CPU utilization is still looking good with coverband running, but not tracking gems. The high load seems to have been caused either by the gem tracking, or by having a bunch of old data in our redis.

**Comment by kbaum** [comment] 2019-05-15 14:07
@jagthedrummer Are you sure high cpu is not caused by the custom middleware you had in place? I think with the custom middleware, coverband was sending data to redis on every sidekiq job execution. Without the custom middleware, coverband will automatically send data to redis every 30 seconds in a background thread.

**Comment by jagthedrummer** [comment] 2019-05-15 14:13
I suppose theoretically the middleware _could_ be at play, but we were seeing increased load on non-sidekiq dynos, so that seems unlikely to me. Though it could be that I don't fully understand how the middleware was getting hooked up or being called or something...

**Comment by kbaum** [comment] 2019-05-15 14:31
Ok. The latest coverband rack middleware does not report directly to redis. It only kicks off the background thread on first request. It seems like tracking gems might be behind the increased CPU usage. Would be great to be able to reproduce this with a benchmark test. Would you be able to let us know how many gems your rails application uses?

**Comment by jagthedrummer** [comment] 2019-05-15 14:36
We have 243 gems listed in `Gemfile` and running `bundle list` outputs 461 unique gems.

**Comment by danmayer** [comment] 2019-05-15 15:25
Glad to hear it is working well. Did you attempt to turn on Gem tracking again and see high load or it has just worked well but you didn't enable Gem tracking?

I am working on enabling Coverband in a similarly large project with Gem tracking and have been making some other optimizations for Gems. So If you want to wait until I can confirm performance on a large app, no worries.

**Comment by jagthedrummer** [comment] 2019-05-15 16:27
We have not attempted to turn gem tracking back on. I'll have to check with our ops team and see what sort of stomach they have for that. The issue came to a head for us because the increased CPU utilization was seriously inflating dyno start times and leaving the production app in an inconsistent and unpredictable state after each deploy or ENV change. So I suspect they're going to be less than enthusiastic about turning it back on.

**Comment by danmayer** [comment] 2019-05-15 17:02
Cool yeah so I would say leave it off, for now, @jagthedrummer  I just wanted to make sure that we didn't have a confirmed issue, just that we suspect it could still be an issue.

I should be able to better benchmark the gem performance and give a thumbs up for wider usage after the next release. Perhaps it will be worth it for your team to try that feature again at that time.

**Comment by danmayer** [comment] 2019-05-18 16:05
thanks closing

**Closed by danmayer** 2019-05-18 16:05 UTC
