### ISSUE TITLE
Can we change the keys in redis to start from the app root? 

### ISSUE THREAD

**Issue by ryanclark2** [danmayer/coverband#50] opened 2016-01-29 21:17 UTC
It would be great if this was an option. I'd like to submit a PR with this in it, but am having a hard time slicing in the right spot. Can you a)let me know if this is something you'd be willing to incorporate and b)point me in the right direction to implement it?

**Comment by kbaum** [comment] 2016-01-30 13:08
I think this probably makes sense but what specific problem are you running into?

thx!

**Comment by danmayer** [comment] 2016-01-30 15:12
yeah I am not quite clear why or what the issue is?

**Comment by iamryo** [comment] 2016-01-30 17:23
We deploy multiple times per day and only keep the most recent 5 releases
on the production servers. This causes a lot of the keys in redis to point
at files in directories that no longer exist.

Relatedly, it would be nice to be able to specify where the baseline json
file goes. I know there's another issue to put it in redis. I'd love to
work on that too since we run into issues there as well.

**Comment by kbaum** [comment] 2016-01-30 21:47
Silly question. What is the use case for baseline file? Thx.

**Comment by iamryo** [comment] 2016-01-30 23:01
Having created a baseline file in production when the gem was first
installed and deployed, its gone when we go back in to generate a report.
It would be great if that was still available after a bunch of code pushes.

I've thought a bit more about this today and realize that the current
approach kind of fingerprints the files so that if they change the line
numbers don't get messed up. That makes sense, but I'd also say we're not
going to be looking to delete code from recently changed files. The ones we
want to identify are likely to not have changed for a while. For our use
case we just want coverband to be able to run continuously through many
deployments.

I also, after looking through the code, realize we can run the baseline
task at any time without it affecting the reporting. That's not immediately
clear from the readme.

Happy to submit a PR to add more info.

**Comment by danmayer** [comment] 2016-01-30 23:40
um clearly there is confusion here... The baseline should be recorded in development and is merged when one pulls the production data for a full report. The purpose of the baseline is to capture all code executed during app boot. For perf reasons with the option to sleep through the first few requests Coverband during deployment would never capture the execution of things like method definitions without the baseline recording merged in....

There are options and controls so that all the stats work across deploys including path changes for the deploy directory. Some of the design was specifically to address this, as I was hitting that issue... Could you give a bit more information, as it seems there is either a misconfiguration or a new bug. The below code should be helping resolve this. 

https://github.com/danmayer/coverband/blob/master/lib/coverband/reporter.rb#L68

Did you configure the root as part of the configuration file?

```
Coverband.configure do |config|
  config.root              = Dir.pwd
```

**Comment by danmayer** [comment] 2016-01-30 23:43
Ahh just read the most recent response @iamryo yeah you can run the baseline over and over when ever needed. You are correct that it is trying to keep coverage across multiple deploys the reason being is some code might only get called on a weekly/monthly basis for reports. So while files are changing the goal would be able to still capture those long tail changes across deploys for files that don't change often. This can lead to bad data on frequently changing files, I also don't worry about files that are changing fast and frequently.

**Comment by iamryo** [comment] 2016-02-01 17:42
@danmayer We do set the `config.root` (copied over from the config in the readme). We also set the `config.root_paths`. I'm not sure what the difference is between the two? I think we haven't yet tried deploying with the `config.root_paths` set to regex out the `releases/<release>/` path. I didn't think that was going to work since the entire path was still showing up in redis, but I guess that's how it's supposed to work and it fixes the file paths when the report gets created?

**Comment by iamryo** [comment] 2016-04-07 21:37
@danmayer @kbaum I will probably have some time tomorrow to work on this and/or other issues. I'd also like to work on the readme/wiki if everyone's ok with that. Do either of you have time to chat tomorrow?

**Comment by kbaum** [comment] 2016-04-11 12:03
@iamryo - apologize, just getting to this now.  I am not that knowledgable on this specific issue though so i doubt i would be able to help.

**Comment by danmayer** [comment] 2016-04-14 17:06
Hey sorry late as well. It still sounds like a filtering problem as all the keys should just be relative path and you are getting a full path. That way it wouldn't point to old files... If you have some file paths and names I might be able to help more. I do worry that when we made some changes for performance improvements we could have broken the regex filter for the release folders, which is what we would need to try to determine. A list of some paths could help us try to replicate with a test.

**Comment by danmayer** [comment] 2017-01-05 02:52
I will look at this for 2.0 and it should be doable...

**Comment by ryanclark2** [comment] 2017-01-05 04:39
Awesome, thanks!

**Comment by danmayer** [comment] 2018-08-05 20:24
OK added some documentation on the various internal paths use by Coverband to the Readme

https://github.com/danmayer/coverband#internal-formats

We actually are storing all the paths as relative in Redis (definitely in 2.0 and I believe in the past). I believe if you were seeing duplicate files based on the deployed file location changing the `config.root` or `config.root_paths` would be the correct solution. I would be happy to get this made more clear in the documentation or setup, but not sure how to help without some more details/example Redis keys or file paths.

The other part of this issues is related to taking baseline snapshots on different systems. I think the best way to resolve that will be dropping baseline as a requirement. I am working on doing that in the next couple weeks.

**Closed by danmayer** 2018-08-05 20:24 UTC

**Comment by ryanclark2** [comment] 2018-08-06 17:54
Hey Dan, 

Thanks for following up on this. I've moved on from the project I was on when I opened this, but will add Coverband to our current app and see how things go. If anything comes up, I'll reach out.

**Comment by danmayer** [comment] 2018-08-07 01:55
Awesome sounds good @ryanclark2 hopefully with improved docs and more recent rails examples it is easy to get up and going without issues. 

The readme should be good, but if you are looking into any issues, I am working on building out a Heroku deployable demo site the initial configuration might be helpful. Currently, have only been running it on localhost.

https://github.com/danmayer/coverband_demo
