### ISSUE TITLE
Unexpected tail latency increase from Coverband

### ISSUE THREAD

**Issue by blakewest** [danmayer/coverband#327] opened 2019-10-03 20:00 UTC
Hey! Wanted to follow up. We fixed [our issue](https://github.com/danmayer/coverband/issues/312) from a while ago. We also added some metrics to determine the impact of Coverband. I wanted to bring up our findings as they seem significantly worse than the [blog post benchmarks](https://www.mayerdan.com/ruby/2018/10/03/coverband-3). I know that post is a year old, (exactly actually), and Coverband is on v4 now, but it seems to be the latest benchmark figures, so it's what I was hoping to see.

What we found was that the 50th percentile for "No Coverband" vs. "Coverband" is about what the blogpost mentions, but the tail latency is quite sizeable. As you go up in the percentiles of each, you see progressively worse relative performance. See below...

![image](https://user-images.githubusercontent.com/2524396/66156255-2bac8780-e5d6-11e9-9efa-b8b9cef9642e.png)

To help you parse that... the "group" is on the right. Notice, it's 3 pairs of "coverband:false", and "coverband: true". The first pair represent false/true of 50th percentile. The next pair is false/true of 75th percentile, and finally 99th percentile. 

The numbers are total request time in ms, for all requests coming through the middleware, and we log it in a request-end middleware. These stats were gleaned over a 4-hour period with 5 min rollup on Datadog. That's about 500 req/min during the 4 hr period hitting Coverband, and far far more hitting as non-coverband. The choosing of Coverband processes is totally random.

Due to the tail latency, we're hesitant to roll out Coverband beyond our very very small percentage of processes that we currently have. We have no custom configuration on the coverband, save for setting the background sleep time to be 240s instead of 30. We also have no special anything on Coverband. We removed all that after the previous discussion, and went with a `require: false` + use a random number threshold to gate doing the `require` inside `application.rb` as our way of "turning on" Coverband. 

Curious what your thoughts are. Is this expected? Any way to decrease the tail latency?

PS: It would be cool if you had a built in mechanism for doing process or thread based activation thresholds. Eg. roll out to 0.5% of your processes, or threads.

**Comment by danmayer** [comment] 2019-10-03 23:18
hmmm interesting thanks for sharing @blakewest I will have to think a bit to see if I can come up with what might be going on... I really appreciate the time to share this information back to the project.

I have some benchmark tests but they are low level. I haven't done any performance tests for a while as we have been more focused on memory usage, correctness,  & ease of use / setup for the last while. Also, we are running it on hundreds of servers and didn't notice any impact so it isn't something I have been investigating for some time. I can perhaps think of a few things that could significantly improve performance... Sadly, so much can be dependant on the setup/environment it is hard to know where the issue lies for sure.

You might have answered previously, but if you could give some details it could help:

* ruby version
* rails version
* server info (puma, unicorn, etc)...
     * some info if it is configured to be fork/process heavy vs thread usage
     * basically, Coverband does better with fewer processes and more threads (as it can leverage shared memory better)
* is it a dedicated or shared Redis?

Funny about the percentage based rollout, we used to support that feature. Initially, Coverband was always developed to be deployed with request sampling... but as the performance overhead continued to shrink and the value of having 100% correctness of code usage increased, that was dropped. I haven't faced recent reports of performance issues, that couldn't be resolved, which is why that feature was removed some time ago, and most benchmarking has moved to the memory side of things.

I do believe since I have done my perf reporting there may have been some slight regressions, mostly related to the correctness or trading a bit of CPU to reduce memory... I could try to do some better CPU 
benchmarks again sometime soon, but I think there are a few things to try first.

1. You say you have it in hour application.rb, I am guessing it is some random number, sets a toggle that logs and turns on Coverband... Please ENSURE IT IS AFTER BUNDLER, otherwise, you will incur all the costs of gem tracking, which you aren't using. This would be an awesome quick fix if the ordering issue is the problem.

```
# THIS SHOULD BE FIRST IN THE FILE
Bundler.require(*Rails.groups) if defined?(Bundler)
# THIS SHOULD BE AFTER bundler and any other requires that you don't want to be tracked
require 'coverband' if COVERBAND_ENABLED_FLAG
```

2. I believe the code is toggling the Coverband require statement, and not something like `Coverband.start` or `use middleware`. Make sure that is true otherwise you will still have much of the overhead in both cases

3. Look at your Coverband results (preferably the raw JSON via the `config.web_debug = true` setting and see if there is some large set of files that should be ignored... For example, are you showing coverage for a `vendor`, weird `library` or something like `std_lib`. I have seen odd deployment setups end up trying to track coverage for all ruby files, all gems, or relatively mounted projects (lots of files with 0% hits). If this is the case it can likely be fixed by modifying your Coverband config... `config.ignore = ['/usr/local/bundle']`

4. If you are on Ruby 2.6, it would be worth trying the oneshot support, let me know if you are and I can explain that in more detail.

5. If you have the machines or data tagged with Coverband check out the memory / CPU of the machines with it enabled opposed to just the response time. If you are close to full load CPU or memory perhaps Coverband is just pushing it over the edge. On one deployment the memory increase was enough that we reduced the number of processes by one to keep memory at an acceptable level. The crazy 4.5K tail could be a machine that is running out of memory and is GC'ing / disk swapping / etc like crazy... The perf could go back to expected ranges if resources were kept to acceptable levels... If memory is the issue we can talk about an alternative storage mechanism we have that is lower memory and CPU on the Ruby client, but increases the demands for a more powerful redis server.

---

Without other info, those are my best guesses for now... Ruby can be affected by a lot of things outside of the Gems control and in this case, it is hard to know what the issue is without digging in a bit more.

If none of the tips I gave help, I would recommend seeing what the impact of the raw Coverage library is on your app... basically use the same random toggle you have, but opposed to requiring Coverband run these two lines.

```
require 'coverage'
::Coverage.start
```

Then log all your stats the same way... This won't run Coverband but runs the underlying Ruby standard library I rely on, much of our overhead is from that library. If it slows down when you just require that, it points to either it happening too early in your app initialization process, memory increases due to Coverage could be overwhelming your server load, or your app has some odd runtime characteristics where tracking incurs more overhead than expected.

**Comment by danmayer** [comment] 2019-10-11 18:20
any updates or word on this @blakewest

**Comment by blakewest** [comment] 2019-10-11 23:10
hey @danmayer, yeah sorry for delay. So first off, thanks so much for the thorough response! Here's the update...

To answer your questions...
1.) Ruby 2.6.5
2.) Rails 5.1.6.2
3.) Server: Puma. I believe we are more fork/process heavy. But we also don't see a lot of memory pressure on the machines. So I think it's fine.
4.) Dedicated redis for Coverband.

For the things you said to try first...
1.) Yes it's after bundler.
2.) Yes we're just toggling the requiring of Coverband
3.) I don't think so. I didn't look at the raw json. But in looking at the web UI list of files, we have 3200+ files, and only 16 appear to have zero coverage.
4.) One-shot support could be interesting. I know of it conceptually, and seems cool, though getting an exact count of lines seems better. But how do we get it working with Coverband?
5.) We looked into this idea, and it seemed promising, but the stats just don't bear it out. We looked at a couple machines running Coverband, and their memory pressure seemed totally fine. Can't say we exhaustively looked at every machine, or over many many time periods, but we spot checked a few, and it didn't seem worth pursuing further.

One other theory we came to is that we use a non-standard garbage collector that actually tries to reclaim memory over time. This was a purposeful choice that allows us to run more processes on a single box, at the price of slightly degraded performance. It's possible Coverband is forcing it to triggering more GC's, and causing some of the requests to have extra latency. 

Also, we bumped down our "background thread wait time" to 30s (from 240), hoping that perhaps smaller, more consistent flushes would help things, but no luck.

Have you ever tested Coverband with alternative garbage collectors? Seems like a long shot, but thought I'd ask. We might be able to dig into some traces, and see if we can correlate that with a GC sweep, but that might be tough to pinpoint. 

One-shot might be our best bet from here, unless you have other thoughts?

**Comment by kbaum** [comment] 2019-10-11 23:54
I think @danmayer's suggestion of just enabling code coverage tracking instead of coverband is a great experiment as it would help to diagnose whether it's something in the coverband code causing the trouble or just the ruby stdlib coverage library which coverband relies on.

```
require 'coverage'
::Coverage.start
```

**Comment by danmayer** [comment] 2019-10-15 03:04
Thanks for all the details @blakewest I agree if you can benchmark just with `coverage` not `coverband` and see if you are having the same long tail issue.

I haven't tried with any alternative garbage collectors, so there is a chance that could be doing something odd or unexpected...

I am a bit confused on the memory as you said you weren't seeing any memory pressure, but you also have the different memory collectors and think the issue could be GC related right?

> we have 3200+ files, and only 16 appear to have zero coverage.
 
This seems like a really high number of application files, many of the larger monorails I have been looking at are in the  300-500 files...  I am guessing this is the issue, the merge of previous and new coverage data of 3200 files would be CPU and memory intensive and I could see it slowing down the machine. So I would like to try to understand, what they all our... 

* again looking at the raw might help you see a bunch of files that aren't app code...
* just browsing through the view with 3.2K files
    * is it showing things like activerecord / or rails files?
    * standard lib ruby files? Things like CSV, JSON, etc
    * vendor files? Normally these should be excluded
    * spec / test files appearing in the data?
    * migration / DB files?
   
If you could perhaps break things down into around how many files are in each top level directory perhaps I could help see something that should be excluded... Are there any files you see while browsing that you wouldn't consider valuable to have coverage tracking on?

Some list like
```
app/models 42 files
app/controllers 30 files
config/initializers 15 files
etc... 
 ```

If there are really 3200 application Ruby files, I don't think oneshot would really help you as I belive the data merging iss the issue... If you want to try oneshot since you are on Ruby 2.6.x you just enable it via a config `config.use_oneshot_lines_coverage = true`. This reduces the overhead introduced with `Coverage`, but won't help with the merge.

I have one other idea that could help with the merge, but before looking at that let me know a bit more details about that total file count.

**Comment by danmayer** [comment] 2019-10-18 15:34
any other info on the large fileset @blakewest

**Comment by blakewest** [comment] 2019-10-21 18:58
@danmayer Sorry for delay. I'm fitting this in between "real" work. Anyway... I looked through the file list. To be honest, I'm surprised it's not more files! Here's a flavor of our file count by folder...

```
blakewest@Blake-West:(master)$ find ./app/views/ -print | wc -l
    1847
blakewest@Blake-West:(master)$ find ./lib -print | wc -l
    1419
blakewest@Blake-West:(master)$ find ./app/models/ -print | wc -l
     614
blakewest@Blake-West:(master)$ find ./app/jobs/ -print | wc -l
     507
blakewest@Blake-West:(master)$ find ./app/controllers/ -print | wc -l
     492
blakewest@Blake-West:(master)$ find ./app/presenters/ -print | wc -l
     232
blakewest@Blake-West: (master)$ find ./app/view_models/ -print | wc -l
       2
blakewest@Blake-West: (master)$ find ./app/receivers/ -print | wc -l
      61
blakewest@Blake-West:(master)$ find ./app/services/ -print | wc -l
     200
```

So clearly there's way more than 3200 application files. It's a big rails app! Coverband is only picking up on about 3200 though, I guess because of load ordering? 

In any event, I also looked through the list that Coverband is picking up on from the Web UI, and that list does not include any of the things you mentioned, such as vendor files, specs, active record, csv's, etc. 

I think we legitimately just have a ton of files. 

Trying out using only the `Coverage` module would be easy, but it sounds like you're saying it wouldn't really help. And perhaps our best bet would be to try and exclude many of our files? (which obviously reduces the benefit of Coverband). But hmm.. so yeah at this point we may just have to live with sampling. Do you have other thoughts?

**Comment by danmayer** [comment] 2019-10-21 20:17
awesome thanks @blakewest this is helpful... Most of your folders look pretty normal, but the views and lib look a bit odd so a bit more info might help.

The views folder is big (and often is), but as noted in the readme Coverband can't track view file Lines of code, so it shouldn't be showing them or trying to track them in Coverband at all... I am guessing that is a big part of the slowdown.  I am guessing you are using something other than ERB, like `slim` or `haml` so it isn't getting excluded by default... I guess you listed just file count from your local machine is anything in `app/views` showing in the Coverband UI?

We do have a view tracking feature, but it tracks only the file level not the line of code level and is much more efficient. I would try to get all the normal Coverage running before enabling this. https://github.com/danmayer/coverband#view-tracking

So I think you want to add your view file type to exclude...

```
  config.ignore = %w[config/application.rb
                     config/boot.rb
                     *.haml
                     *.slim
                     etc_whatever_builders_and_templates_you_use
```

The lib folder also looks weirdly large to me... Do you have things like git submodule libraries or gems in there? could you share some more details about the high-level types of things in there? Perhaps I will be able to see something that I wouldn't expect to track. I guess again only caring about lib files that show up in Coverband UI, vs local count, as it could filter some out. 

> Trying out using only the Coverage module would be easy, but it sounds like you're saying it wouldn't really help. And perhaps our best bet would be to try and exclude many of our files? (which obviously reduces the benefit of Coverband). But hmm.. so yeah at this point we may just have to live with sampling. Do you have other thoughts?

This would still be really helpful as it would let us know if tuning Coverband correctly would ever make it viable for y'all or if just the underlying library causes too much overhead. If you can run in this mode without any tail latency, then we should be able to fix all the issues you are having with Coverband.

**Comment by danmayer** [comment] 2020-08-30 21:51
OK @blakewest it has been open for awhile, I did some significant changes in Coverband 5.0 that should help with addressing tail latency. If you want to give it another shot let me know if you still see issues with an impact to tail latency. I am going to close this out as I can run on fairly large production systems without being able to detect tail latency issues with the latest release and options.

**Closed by danmayer** 2020-08-30 21:51 UTC
